"use client";
import { useEffect, useState } from "react";
import { Bookmark, Heart, Star } from "lucide-react";
import * as api from "@/lib/api";
import { useAuth } from "@/context/AuthContext";
import { useToast } from "@/components/ToastProvider";
import type { Destination, DestinationReview } from "@/lib/types";

function Stars({ value, onChange }: { value: number; onChange?: (value: number) => void }) { return <div className="flex gap-1">{[1, 2, 3, 4, 5].map((star) => <button key={star} type="button" disabled={!onChange} onClick={() => onChange?.(star)} aria-label={`${star} stars`} className="disabled:cursor-default"><Star size={onChange ? 24 : 17} fill={star <= value ? "currentColor" : "none"} className="text-marigold-dark" /></button>)}</div>; }

export default function DestinationInteractions({ destination, onUpdate }: { destination: Destination; onUpdate: (destination: Destination) => void }) {
 const { token, user, updateUser } = useAuth(); const toast = useToast(); const [reviews, setReviews] = useState<DestinationReview[]>([]); const [loading, setLoading] = useState(true); const [rating, setRating] = useState(0); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false); const [liked, setLiked] = useState(destination.liked_by_current_user); const [likes, setLikes] = useState(destination.like_count); const [favorite, setFavorite] = useState(user?.favorites.includes(destination.id) || false);
 useEffect(() => { api.getReviews(destination.id).then(setReviews).finally(() => setLoading(false)); }, [destination.id]);
 async function like() { if (!token) return; setBusy(true); try { const result = await api.toggleLike(destination.id, token); setLiked(result.liked); setLikes(result.like_count); onUpdate({ ...destination, like_count: result.like_count, liked_by_current_user: result.liked }); toast.success(result.liked ? "Place liked." : "Like removed."); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not update like."); } finally { setBusy(false); } }
 async function saveFavorite() { if (!token || !user) return; setBusy(true); try { const result = await api.toggleFavorite(destination.id, token); setFavorite(result.favorite); updateUser({ ...user, favorites: result.favorites }); toast.success(result.favorite ? "Saved to your favorites." : "Removed from favorites."); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not update favorite."); } finally { setBusy(false); } }
 async function submit(e: React.FormEvent) { e.preventDefault(); if (!token || !rating || !comment.trim()) return toast.error("Choose a star rating and write a comment."); setBusy(true); try { const review = await api.addReview(destination.id, { rating, comment: comment.trim() }, token); const next = [review, ...reviews]; setReviews(next); const average = next.reduce((sum, item) => sum + item.rating, 0) / next.length; onUpdate({ ...destination, rating: Number(average.toFixed(1)), review_count: next.length }); setRating(0); setComment(""); toast.success("Your review was published."); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not submit review."); } finally { setBusy(false); } }
 return <section className="mt-10 grid gap-6 lg:grid-cols-5"><div className="lg:col-span-2 rounded-card bg-white p-5 shadow-card"><div className="flex items-center justify-between"><div><h2 className="font-display text-2xl text-canopy">Community rating</h2><div className="mt-2 flex items-center gap-2"><Stars value={Math.round(destination.rating)} /><b>{destination.rating.toFixed(1)}</b><span className="text-sm text-ink/55">({destination.review_count} reviews)</span></div></div></div><div className="mt-5 flex gap-3"><button disabled={busy} onClick={like} className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold ${liked ? "border-laterite bg-laterite/10 text-laterite" : "border-canopy/20 text-canopy"}`}><Heart size={17} fill={liked ? "currentColor" : "none"} />{likes}</button><button disabled={busy} onClick={saveFavorite} className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold ${favorite ? "border-canopy bg-canopy text-white" : "border-canopy/20 text-canopy"}`}><Bookmark size={17} fill={favorite ? "currentColor" : "none"} />{favorite ? "Saved" : "Save"}</button></div><form onSubmit={submit} className="mt-6 border-t border-canopy/10 pt-5"><h3 className="font-semibold text-canopy">Leave a review</h3><div className="mt-2"><Stars value={rating} onChange={setRating} /></div><textarea value={comment} onChange={(e) => setComment(e.target.value)} maxLength={2000} placeholder="Share what you enjoyed…" className="mt-3 w-full rounded-lg border border-canopy/20 p-3 text-sm" rows={4} /><button disabled={busy} className="mt-3 rounded-full bg-laterite px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Post review</button></form></div><div className="lg:col-span-3 rounded-card bg-white p-5 shadow-card"><h2 className="font-display text-2xl text-canopy">Visitor reviews</h2>{loading ? <div className="mt-4 space-y-3">{[1,2,3].map((i) => <div key={i} className="h-20 animate-pulse rounded-lg bg-canopy/5" />)}</div> : reviews.length ? <div className="mt-4 space-y-4">{reviews.map((review) => <article key={review.id} className="border-b border-canopy/10 pb-4 last:border-0"><div className="flex items-center justify-between"><b>{review.user_name}</b><Stars value={review.rating} /></div><p className="mt-2 text-sm text-ink/75">{review.comment}</p><p className="mt-2 text-xs text-ink/45">{new Date(review.created_at).toLocaleDateString()}</p></article>)}</div> : <p className="mt-4 text-sm text-ink/60">Be the first to share a review.</p>}</div></section>;
}
