"use client";

import { FormEvent, useEffect, useState } from "react";
import Navbar from "@/components/Navbar";
import Spinner from "@/components/Spinner";
import { useAuth } from "@/context/AuthContext";
import * as api from "@/lib/api";
import type { CommunityPost } from "@/lib/types";

function CommunityContent() {
  const { token, user } = useAuth(); const [posts, setPosts] = useState<CommunityPost[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [form, setForm] = useState({ title: "", location_tag: "", body: "" }); const [comments, setComments] = useState<Record<string, string>>({});
  useEffect(() => { api.getCommunityPosts().then(setPosts).catch(() => setError("Could not load community stories.")).finally(() => setLoading(false)); }, []);
  async function publish(event: FormEvent) { event.preventDefault(); if (!token) return; try { const post = await api.createCommunityPost(form, token); setPosts((items) => [post, ...items]); setForm({ title: "", location_tag: "", body: "" }); } catch (err) { setError(err instanceof Error ? err.message : "Could not publish your post."); } }
  async function comment(id: string) { if (!token || !comments[id]?.trim()) return; try { const updated = await api.addCommunityComment(id, comments[id], token); setPosts((items) => items.map((item) => item.id === id ? updated : item)); setComments({ ...comments, [id]: "" }); } catch (err) { setError(err instanceof Error ? err.message : "Could not post comment."); } }
  return <div className="min-h-screen bg-ivory"><Navbar /><main className="max-w-3xl mx-auto px-4 sm:px-6 py-10"><p className="font-stamp uppercase tracking-wider text-xs text-laterite">Yaoundé Community</p><h1 className="font-display text-4xl text-canopy mt-2">Stories, tips & local discoveries</h1><p className="text-ink/60 mt-2 mb-8">Share practical experiences with fellow travellers.</p>{user ? <form onSubmit={publish} className="bg-white shadow-card rounded-card p-5 mb-8 space-y-3"><h2 className="font-display text-xl text-canopy">Share an experience</h2><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="A useful title" className="w-full rounded-lg border border-canopy/20 px-3 py-2" /><input required value={form.location_tag} onChange={(e) => setForm({ ...form, location_tag: e.target.value })} placeholder="Tag a Yaoundé location" className="w-full rounded-lg border border-canopy/20 px-3 py-2" /><textarea required rows={4} value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} placeholder="Tell fellow travellers what you discovered…" className="w-full rounded-lg border border-canopy/20 px-3 py-2" /><button className="rounded-full bg-laterite text-white px-5 py-2.5 text-sm font-semibold">Publish story</button></form> : <p className="bg-white rounded-card shadow-card p-4 mb-8 text-sm text-ink/65">Sign in to publish a story or comment.</p>}{error && <p className="mb-4 text-sm text-laterite">{error}</p>}{loading ? <div className="py-16 flex justify-center"><Spinner label="Loading stories" /></div> : <div className="space-y-5">{posts.length === 0 && <p className="text-ink/55 text-center py-12">Be the first to share a Yaoundé travel tip.</p>}{posts.map((post) => <article key={post.id} className="bg-white rounded-card shadow-card p-5"><div className="flex justify-between gap-3 text-sm"><span className="font-semibold text-canopy">{post.user_name}</span><span className="text-ink/45">{new Date(post.timestamp).toLocaleDateString()}</span></div><span className="inline-block mt-2 text-xs bg-marigold/20 px-2 py-1 rounded-full">📍 {post.location_tag}</span><h2 className="font-display text-2xl text-ink mt-3">{post.title}</h2><p className="text-ink/75 mt-2 whitespace-pre-wrap">{post.body}</p><div className="mt-5 border-t border-canopy/10 pt-4 space-y-3">{post.comments.map((item) => <div key={item.id} className="text-sm"><b className="text-canopy">{item.user_name}: </b><span className="text-ink/70">{item.body}</span></div>)}{token && <div className="flex gap-2"><input value={comments[post.id] || ""} onChange={(e) => setComments({ ...comments, [post.id]: e.target.value })} placeholder="Add a comment" className="flex-1 rounded-lg border border-canopy/20 px-3 py-2 text-sm" /><button type="button" onClick={() => comment(post.id)} className="text-sm font-semibold text-laterite">Reply</button></div>}</div></article>)}</div>}</main></div>;
}
export default function CommunityPage() { return <CommunityContent />; }
